export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export const LOAD_COUNTRIES_SUCCESS = 'LOAD_COUNTRIES_SUCCESS_FULFILLED';

export const LOAD_COUNTRIES_SUCCESS_PENDING = `${LOAD_COUNTRIES_SUCCESS}_PENDING`;
export const LOAD_COUNTRIES_SUCCESS_REJECTED = `${LOAD_COUNTRIES_SUCCESS}_REJECTED`;
export const LOAD_COUNTRIES_SUCCESS_FULFILLED = `${LOAD_COUNTRIES_SUCCESS}_FULFILLED`;

// Action Constants
export const DELETE_COUNTRIES_SUCCESS = 'DELETE_COUNTRIES_SUCCESS';

// Action Creators
export const DELETE_COUNTRIES_SUCCESS_PENDING = `${DELETE_COUNTRIES_SUCCESS}_PENDING`;
export const DELETE_COUNTRIES_SUCCESS_REJECTED = `${DELETE_COUNTRIES_SUCCESS}_REJECTED`;
export const DELETE_COUNTRIES_SUCCESS_FULFILLED = `${DELETE_COUNTRIES_SUCCESS}_FULFILLED`;

export const LOAD_CITIES_SUCCESS = 'LOAD_CITIES_SUCCESS';

export const CREATE_COURSES_SUCCESS = 'CREATE_COURSES_SUCCESS';
export const UPDATE_COURSES_SUCCESS = 'UPDATE_COURSES_SUCCESS';
