export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export const LOAD_COUNTRIES_SUCCESS = 'LOAD_COUNTRIES_SUCCESS';
export const LOAD_COUNTRIES_SUCCESS_PENDING = `${LOAD_COUNTRIES_SUCCESS}_PENDING`;
export const LOAD_COUNTRIES_SUCCESS_REJECTED = `${LOAD_COUNTRIES_SUCCESS}_REJECTED`;
export const LOAD_COUNTRIES_SUCCESS_FULFILLED = `${LOAD_COUNTRIES_SUCCESS}_FULFILLED`;

export const SAVE_COUNTRIES_SUCCESS = 'SAVE_COUNTRIES_SUCCESS';
export const SAVE_COUNTRIES_SUCCESS_PENDING = `${SAVE_COUNTRIES_SUCCESS}_PENDING`;
export const SAVE_COUNTRIES_SUCCESS_REJECTED = `${SAVE_COUNTRIES_SUCCESS}_REJECTED`;
export const SAVE_COUNTRIES_SUCCESS_FULFILLED = `${SAVE_COUNTRIES_SUCCESS}_FULFILLED`;

export const UPDATE_COUNTRIES_SUCCESS = 'UPDATE_COUNTRIES_SUCCESS';

export const DELETE_COUNTRIES_SUCCESS = 'DELETE_COUNTRIES_SUCCESS';
export const DELETE_COUNTRIES_SUCCESS_PENDING = `${DELETE_COUNTRIES_SUCCESS}_PENDING`;
export const DELETE_COUNTRIES_SUCCESS_REJECTED = `${DELETE_COUNTRIES_SUCCESS}_REJECTED`;
export const DELETE_COUNTRIES_SUCCESS_FULFILLED = `${DELETE_COUNTRIES_SUCCESS}_FULFILLED`;

export const LOAD_CITIES_SUCCESS = 'LOAD_CITIES_SUCCESS';

export const CREATE_COURSES_SUCCESS = 'CREATE_COURSES_SUCCESS';
export const UPDATE_COURSES_SUCCESS = 'UPDATE_COURSES_SUCCESS';

export const POUCH_REQUEST_FETCH_ALL_NOTES = 'POUCH_REQUEST_FETCH_ALL_NOTES';
export const POUCH_RECEIVE_FETCH_ALL_NOTES = 'POUCH_RECEIVE_FETCH_ALL_NOTES';
export const POUCH_REQUEST_PUT_NOTE = 'POUCH_REQUEST_PUT_NOTE';
export const POUCH_RECEIVE_PUT_NOTE = 'POUCH_RECEIVE_PUT_NOTE';
export const POUCH_REQUEST_GET_NOTE = 'POUCH_REQUEST_GET_NOTE';
export const POUCH_RECEIVE_GET_NOTE = 'POUCH_RECEIVE_GET_NOTE';
